#deposer une annonce

ChoixCategorie="xpath://div[@class='select' and @data-type='1']"
selectAutoMoto="xpath://li[@data-value='V']"
selectVoitureOccasion="xpath://li[@data-value='VVO00000']"
SelectEvenement="xpath://li[@data-value='BEV00000']"
SelectVsansPermis="xpath://li[@data-value='VZZVP000']"
selectparticulier="xpath://input[@id='private_ad_id']"
selectprofessionel="xpath://input[@id='company_ad_id']"
selectcaracterisuque="xpath://input[@class='checkbox' and @value='manuelle' ]"
IDTypevehicul= "typeVehicule"
IdMarque="marque"
IDmodel="modele"
Idmois="mois"
idannee="annee"
IdCarrosserie="id:type"
IdEnergie="energie"
idtransmmision="typeTransmission"
idnbrporte="xpath://select[@id='nombrePortes']"
idversion="version"
idkilometrage="xpath://input[@id='kilometrage']"
idEmissionCO2="xpath://input[@id='enrichi-7800001_150']"
idcouleurcarrosserie="xpath://select[@id='enrichi-7800001_10']"
idvignettedair="xpath://select[@id='enrichi-7800001_190']"
idpremiermain="xpath://label[@for='enrichi-7800001_60_1'  and @class='coche']"
Selectprixnegociable="xpath://label[@for='flagPrixNegociable' and @class='coche']"
idprix="id:prix"
cochePrixnegociable="xpath://label[@for='flagPrixNegociable']"
idpays="id:codePays"
idcommune="id:communeLibre"
telechargerphoto="xpath://span[@class='depresp17-btn btn-dlphotos']"
